### ISSUE TITLE
Low quality icon

### ISSUE THREAD

**Issue by garrett** [flathub/org.kde.kcachegrind#1]
KCachegrind has a blurry, low quality PNG as an icon. (I noticed it's the one in the source code of the app. @ https://invent.kde.org/sdk/kcachegrind/-/tree/master/kcachegrind)

However, KDE's official applications page has another icon in use for KCachegrind... it's a completely different, more modern style and it's in an SVG too.

- Official page: https://kde.org/applications/en/development/org.kde.kcachegrind
- SVG icon: https://kde.org/applications/icons/org.kde.kcachegrind.svg

I'm not sure why this one isn't in the source code of the application, but it's pretty clear it's the icon that should be used for the application. I guess it's ordinarily pulled in via an icon theme? Can Flathub use the SVG instead?

**Comment by bilelmoussaoui** [comment]
We tend to avoid any changes of that kind, I suggest opening an issue upstream about updating the icon or at least offering a higher resolution version of it. We can backport that patch here meanwhile if needed.

**Comment by tsdgeos** [comment]
The kde.org/Applications page os the one from the breeze iconset [1] which i've already complained multiple times it's a terrible idea to use that iconset in the page since it overwrites the actual application icon, but that's kind of off topic here :D

If you want to suggest importing the breeze icon to kcachegrind that's one option, at least i'd file a bug (remember bugs.kde.org not issues in invent.kde.org) about the icon being blurry

**Comment by Siosm** [comment]
Upstream PR: https://invent.kde.org/sdk/kcachegrind/-/merge_requests/1
Flathub PR: https://github.com/flathub/org.kde.kcachegrind/pull/3

**Comment by Siosm** [comment]
Fixed by latest release.
